INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade a119c69f9a52 -> 91321b2aaf59, Add User model
Traceback (most recent call last):
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 79, in <module>
    run_migrations_online()
  File "migrations/env.py", line 73, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/ziru/Development/code/phase-3/python-p3-sqlalchemy-many-to-many/lib/migrations/versions/91321b2aaf59_add_user_model.py", line 23, in upgrade
    op.create_foreign_key('fk_reviews_users', 'reviews', 'users', ['user_id'], ['id'])
  File "<string>", line 8, in create_foreign_key
  File "<string>", line 3, in create_foreign_key
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/operations/ops.py", line 669, in create_foreign_key
    return operations.invoke(op)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/operations/base.py", line 401, in invoke
    return fn(self, operation)
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 175, in create_constraint
    operations.impl.add_constraint(
  File "/home/ziru/.local/share/virtualenvs/python-p3-sqlalchemy-many-to-many-j_afZ0Dm/lib/python3.8/site-packages/alembic/ddl/sqlite.py", line 75, in add_constraint
    raise NotImplementedError(
NotImplementedError: No support for ALTER of constraints in SQLite dialect. Please refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.